### ISSUE TITLE
Add Support for CC1312 / CC1352 LaunchPad

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc13xx-core#16]
The [SimpleLink™ Multi-Band CC1352R Wireless MCU LaunchPad™ Development Kit](http://www.ti.com/tool/LAUNCHXL-CC1352R1) is replacing the [SimpleLink™ Dual-Band CC1350 Wireless MCU LaunchPad Development Kit](http://www.ti.com/tool/LAUNCHXL-CC1350) with more Flash and more RAM.

| | CC1310 / CC1350 | CC1312 / CC1352 | 
| ---- | ---- | ---- |
| Flash | 128 KB | 352 KB |
| RAM | 20 KB | 80 KB |

Does Energia plan to support those new boards?

**Comment by fcolecumberri** [comment]
+1

**Comment by rei-vilo** [comment]
See https://github.com/energia/cc13x2-core
