### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by battosai30** [energia/cc13xx-core#2]
Hi, 

I have an error trying to compile the Easylink tx (or rx) example : 

> \libraries\EasyLink\src\smartrf_settings\smartrf_settings_predefined.c:36:41: fatal error: rf_patches/rf_patch_rfe_lrm.h: No such file or directory
> 
>  #include <rf_patches/rf_patch_rfe_lrm.h>

Appareltly it's linked with an update of RTOS : https://e2e.ti.com/support/wireless_connectivity/proprietary_sub_1_ghz_simpliciti/f/156/t/553022

EDIT : I downloaded the last RTOS version, searched for rf_patch_rfe_lrm.h and added it to the right place in energia folder and it's ok. So apparently, you just need to update to the last RTOS version

**Comment by robertinant** [comment]
Make sure that you update to the latest CC13xx core. It should be version 3.7.0 that is installed. With version 3.6.1 I was able to reproduce it. Hence your core needs an update to 3.7.0. You can do so through the board manager.

**Comment by battosai30** [comment]
I confirme it's OK with v3.7
