### ISSUE TITLE
The standard `Blynk` example fails to compile because `RED_LED` isn't defined.

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc13xx-core#3]
The standard `Blynk` example fails to compile because `RED_LED` isn't defined.

>    digitalWrite(LED, HIGH);   // turn the LED on (HIGH is the voltage level)
>                 ^
> exit status 1
> 'RED_LED' was not declared in this scope

**Comment by robertinant** [comment]
This is an issue with the compiler flag -DBOARD_{build.board}. build.board is currently set to CC1310_LAUNCHXL / CC1350_LAUNCHXL but cores/cc13xx/ti/runtime/wiring/pins_energia.h expects LAUNCHXL_CC1310 / LAUNCHXL_CC1350 to be able to include the pins_energia.h that is present in the variants directory. Will fix this in the board.txt file.
