### ISSUE TITLE
Flash and RAM sizes are mentioned twice in `boards.txt` with different values.

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc13xx-core#4]
Flash and RAM sizes are mentioned twice in `boards.txt` with different values for **LAUNCHXL_CC1310**.

> LAUNCHXL_CC1310.upload.maximum_size=16384
> LAUNCHXL_CC1310.upload.maximum_size=131072

> LAUNCHXL_CC1310.upload.maximum_ram_size=2560
> LAUNCHXL_CC1310.upload.maximum_data_size=8192

Same for **CC1350STK** and **LAUNCHXL_CC1350**.

**Comment by robertinant** [comment]
fixed with b421f39b8f248a79725652f7e64c365d43db022a
