### ISSUE TITLE
Board Manager and GitHub repository not synchronised

### ISSUE THREAD

**Issue by rei-vilo** [energia/cc13xx-core#6]
The **Board Manager** and the **GitHub repository** are not synchronised.

The **Board Manager** features release 3.7.2...

> **emt-c07 patch level 2**
> version=3.7.2
> version.string=372

... while the **GitHub repository** still contains release 3.7.1.

> **emt-c07 patch level 1**
> version=3.7.1
> version.string=371

This means contribution to this repository are lost. 

For example, 

* The ` -MMD` flag is gone.
* The empty `system/driverlib/CC13xx` folder is back!

**Comment by robertinant** [comment]
I just synchronized the release.
